version: '3'
services:
  app:
    container_name: pretix_app
    build:
      dockerfile: Dockerfile
      context: ./docker/pretix
    restart: always
    depends_on:
      - database
      - cache
    environment:
      - VIRTUAL_HOST=tickets.burn.directory
      - LETSENCRYPT_HOST=tickets.burn.directory

    volumes:
      - pretix_data:/data
      - ./docker/pretix/pretix.cfg:/etc/pretix/pretix.cfg
      - ./docker/pretix/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/pretix/crontab:/tmp/crontab
    ports:
      - "8088:80"
      - "88443"
    networks:
      - default
      - burnertickets

  database:
    image: postgres:16-alpine3.20
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=pretix
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - burnertickets

  cache:
    image: redis:alpine3.20
    container_name: pretix_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - burnertickets

volumes:
  postgres_data:
    driver: local
  pretix_data:
    driver: local

networks:
  default:
    name: nginx-proxy
    external: true
  burnertickets:
    external: false
